content_path: content
template_path: templates
template_static_path: template_assets
filter_paths:
    - custom_filters
    - more_custom_filters

defaults: &defaults
    hover_anchors: "¶"

targets:
    -   name: everything
        display_name: Dactyl Examples
        filters:
            - demote_headers
        demote_headers_pdf_only: true
        stylesheet: template_assets/dactyl.css
        foo: "fooooooo"
        <<: *defaults

    -   name: filterdemos
        display_name: Target with just the filter example pages
        <<: *defaults

    -   name: conditionals
        display_name: Conditional Text Target
        condition: tests-2
        <<: *defaults

pages:
    -   name: Tests
        html: tests-index.html
        category: Tests
        section_header: true
        parent: index.html
        template: landing.html
        targets:
            - everything

    -   md: code-highlighting.md
        html: code-highlighting.html
        parent: tests-index.html
        targets:
            - everything

    -   md: includes.md
        category: Tests
        parent: tests-index.html
        targets:
            - everything

    -   md: with-frontmatter.md
        html: with-frontmatter.html
        parent: tests-index.html
        targets:
            - everything

    -   md: cli-vars.md
        html: cli-vars.html
        parent: tests-index.html
        targets:
            - everything

    -   md: link-types.md
        targets:
            - everything

    -   name: Conditionals Test
        category: Tests
        md: conditionals.md
        parent: tests-index.html
        targets:
            - everything
            - conditionals

    -   name: Lists and Code Blocks Demo
        category: Tests
        md: lists-and-codeblocks.md
        parent: tests-index.html
        targets:
            - everything

    -   name: GitHub Markdown Compatibility
        category: Tests
        md: gfm-compat.md
        parent: tests-index.html
        targets:
            - everything

    -   md: header_stress_test.md
        category: Tests
        parent: tests-index.html
        targets:
            - everything

    -   name: Filters
        category: Filters
        section_header: true
        parent: index.html
        template: landing.html
        targets:
            - everything
            - filterdemos

    -   md: filter-examples/callouts.md
        category: Filters
        parent: filters.html
        targets:
            - everything
            - filterdemos
        filters:
            - callouts

    -   md: filter-examples/xrefs.md
        category: Filters
        parent: filters.html
        targets:
            - everything
            - filterdemos
        filters:
            - xrefs

    -   md: filter-examples/buttonize.md
        category: Filters
        parent: filters.html
        targets:
            - everything
            - filterdemos
        filters:
            - buttonize

    -   md: filter-examples/badges.md
        category: Filters
        parent: filters.html
        targets:
            - everything
            - filterdemos
        filters:
            - badges

    -   md: filter-examples/multicode_tabs.md
        category: Filters
        parent: filters.html
        targets:
            - everything
            - filterdemos
        filters:
            - multicode_tabs

    -   md: extending/index.md
        html: extending-index.html
        category: Extending
        section_header: true
        parent: index.html
        template: landing.html
        targets:
            - everything

    -   md: extending/extend-templates.md
        category: Extending
        parent: extending-index.html
        targets:
            - everything

    -   md: extending/hierarchy.md
        category: Extending
        parent: extending-index.html
        template: template-hierarchy.html
        targets:
            - everything

    -   md: extending/patriots.md
        html: filter-examples-patriots.html
        category: Extending
        parent: extending-index.html
        targets:
            - everything
        filters:
            - patriots

    -   md: extending/patriots.md
        name: Custom Filter 2
        html: filter-examples-patriots2.html
        category: Extending
        parent: extending-index.html
        targets:
            - everything
        filters:
            - patriots2

    -   md: extending/include_code.md
        category: Extending
        parent: extending-index.html
        targets:
            - everything
        filters:
            - include_code

    -   md: extending/debug.md
        html: debug.html
        category: Extending
        parent: extending-index.html
        template: template-minimal.html
        no_highlighting: true
        targets:
            - everything


# -------------------- Style Checker Rules ------------------------
word_substitutions_file: plainlanguage_words.yaml
phrase_substitutions_file: plainlanguage_phrases.yaml
