content_path: content
template_path: templates
template_static_path: template_assets
filter_paths:
    - custom_filters
    - more_custom_filters

defaults: &defaults
    hover_anchors: "¶"
    skip_cover: true

spelling_file: spelling.txt
default_html_names: tail

cover_page:
    html: index.html
    md: index.md
    name: Index
    pdf_template: pdf-cover.html
    template: landing.html

targets:
    -   name: everything
        display_name: "Dactyl: A Heroic Doc Tool"
        filters:
            - demote_headers
        demote_headers_pdf_only: true
        stylesheet: template_assets/dactyl.css
        foo: "fooooooo"
        <<: *defaults

    -   name: filterdemos
        display_name: Target with just the filter example pages
        <<: *defaults

    -   name: conditionals
        display_name: Conditional Text Target
        condition: tests-2
        <<: *defaults

pages:
    -   md: usage/usage.md
    -   md: usage/config.md
    -   md: usage/editing.md
    -   md: usage/link-checking.md
    -   md: usage/style-checking.md
    -   md: usage/elasticsearch.md
    -   md: usage/openapi.md

    -   name: Features
        html: features.html
        category: Features
        section_header: true
        parent: index.html
        template: landing.html
        targets:
            - everything

    -   md: code-highlighting.md
        html: code-highlighting.html
        parent: features.html
        targets:
            - everything

    -   md: includes.md
        category: Features
        parent: features.html
        targets:
            - everything

    -   md: frontmatter.md
        html: frontmatter.html
        parent: features.html
        targets:
            - everything

    -   md: cli-vars.md
        html: cli-vars.html
        parent: features.html
        targets:
            - everything

    -   md: conditionals.md
        category: Features
        parent: features.html
        targets:
            - everything
            - conditionals

    -   name: Lists and Code Blocks Demo
        category: Features
        md: lists-and-codeblocks.md
        parent: features.html
        targets:
            - everything

    -   name: GitHub Markdown Compatibility
        category: Features
        md: gfm-compat.md
        parent: features.html
        targets:
            - everything

    -   md: header_stress_test.md
        category: Features
        parent: features.html
        targets:
            - everything

    -   md: virtual-pages.md
        targets:
            - everything

    -   name: Dactyl Homepage
        parent: virtual-pages.html
        html: https://dactyl.link/#
        blurb: This is a placeholder that shows up in navigation but does not have an actual output file. Use this if you want to link to external resources at a specific place in your navigation.
        targets:
            - everything

    -   md: virtual-placeholder.md
        targets:
            - everything

    -   md: filters/filters.md

    -   md: filters/callouts.md
        category: Filters
        parent: filters.html
        targets:
            - everything
            - filterdemos
        filters:
            - callouts

    -   md: filters/xrefs.md
        category: Filters
        parent: filters.html
        targets:
            - everything
            - filterdemos
        filters:
            - xrefs

    -   md: filters/buttonize.md
        category: Filters
        parent: filters.html
        targets:
            - everything
            - filterdemos
        filters:
            - buttonize

    -   md: filters/badges.md
        category: Filters
        parent: filters.html
        targets:
            - everything
            - filterdemos
        filters:
            - badges

    -   md: filters/multicode_tabs.md
        category: Filters
        parent: filters.html
        targets:
            - everything
            - filterdemos
        filters:
            - multicode_tabs

    -   md: filters/external_links.md
        targets:
            - everything
            - filterdemos

    -   md: extending/index.md
        html: extending-index.html
        category: Extending
        section_header: true
        parent: index.html
        template: landing.html
        targets:
            - everything

    -   md: extending/templates.md
        category: Extending
        parent: extending-index.html
        targets:
            - everything

    -   md: extending/hierarchy.md
        category: Extending
        parent: extending-index.html
        template: template-hierarchy.html
        targets:
            - everything

    -   md: extending/patriots.md
        html: filter-examples-patriots.html
        category: Extending
        parent: extending-index.html
        targets:
            - everything
        filters:
            - patriots

    -   md: extending/patriots.md
        name: Custom Filter 2
        html: filter-examples-patriots2.html
        category: Extending
        parent: extending-index.html
        targets:
            - everything
        filters:
            - patriots2

    -   md: extending/include_code.md
        category: Extending
        parent: extending-index.html
        targets:
            - everything
        filters:
            - include_code

    -   md: extending/debug.md
        html: debug.html
        category: Extending
        parent: extending-index.html
        template: template-minimal.html
        no_highlighting: true
        targets:
            - everything


# -------------------- Style Checker Rules ------------------------
word_substitutions_file: plainlanguage_words.yaml
phrase_substitutions_file: plainlanguage_phrases.yaml
